feat: agregar autenticación y manejo de reportes en el API Gateway co…
salchichongallo/misw4202-202414-arquitectura-agil pull request #31
Opened 2024-09-27 22:37 UTC by Julianrvillamil

…n validación JWT

2024-09-27 23:36 UTC, leinerbarrios requested changes

2024-09-27 23:36 UTC, leinerbarrios commented on experimento-seguridad/microservice-gateway/auth_controller.py
> +                return {'message': 'Credenciales incorrectas'}, response.status_code
El microservicio de auth ya controla los escenarios de login, lo puedes manejar como lo haces en la linea 15.

`
return response.json(), response.status_code
`

De esa manera evitas quemar el mensaje de `Credenciales incorrectas`

2024-09-27 23:36 UTC, leinerbarrios commented on experimento-seguridad/microservice-gateway/main.py
> +app.config['JWT_SECRET_KEY'] = 'frase-secreta'
Por favor valida si la línea 11 es necesaria, ya que el API Gateway no debe generar tokens, lo mismo con la línea 12.

2024-09-27 23:36 UTC, leinerbarrios commented on experimento-seguridad/microservice-gateway/report_controller.py
> +            return make_response({'message': 'Error al obtener el reporte'}, response.status_code)
Acá puedes responder lo mismo de la línea 18.

`
return make_response(response.json(), response.status_code)
`

2024-09-28 13:42 UTC, salchichongallo approved these changes

2024-09-28 14:17 UTC, merged